---
title: "Dashboard dados Penalty"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: lumen
---

```{r setup, include=FALSE}
library(tidyverse)
library(skimr)
library(flexdashboard)
# options(encoding = "WINDOWS-1252")
```

```{r}
dados_jar_emp <- haven::read_spss("dados/penalty/CPT_Avatar_SPSS_reduzido_ADULTO_EMPILHADO.sav")

dados_jar_emp <- dados_jar_emp %>% 
  mutate_all(funs(as.numeric)) 
```


Visão geral
=========================================================

Column {.tabset data-width=2050}
------------------------------------------------

### Estatísticas descritivas

```{r}
dados_jar_emp %>% 
  select(SABOR:PURCHASE) %>%
  skim_to_wide() %>% 
  kable(format = "html")
```

### OL_OVERALL

```{r}
dados_jar_emp %>% 
  ggplot(aes(x = OL_OVERALL)) +
  geom_bar(fill = "orange", color = "black") +
  geom_text(aes(y = ..count.. + 10, label = ..count..), stat = "count") + 
  labs(y = "Frequência") +
  theme_bw()
```

### Sabor em geral

```{r}
dados_jar_emp %>% 
  ggplot(aes(x = JAR_8)) +
  geom_bar(fill = "orange", color = "black") +
  geom_text(aes(y = ..count.. + 15, label = ..count..), stat = "count") + 
  labs(y = "Frequência", x = "Sabor em geral") +
  theme_bw()
```


Column 
------------------------------------------------
### respondentes

```{r}
valueBox(nrow(dados_jar_emp), caption = "Nº respondentes", icon = "fa-users", color = "red")
```

### sabores

```{r}
valueBox(5, icon = "fa-flask")
```

### quesitos

```{r}
valueBox(5, caption = "quesitos", icon = "fa-list")
```

Sabores
================================================

Column {data-width=2050}
------------------------------------------------

### Sabores

```{r}
  p <- dados_jar_emp %>%
    gather(sabor, valor, SAB_BAUNILHA:SAB_MANGA) %>%
    filter(!is.na(valor)) %>% 
    mutate(
      sabor = case_when(
        sabor == "SAB_BANANA" ~ "Banana",
        sabor == "SAB_BAUNILHA" ~ "Baunilha",
        sabor == "SAB_MACA" ~ "Maçã",
        sabor == "SAB_MANGA" ~ "Manga",
        sabor == "SAB_MORANGO" ~ "Morango"
      ),
      valor2 = case_when(
        valor == 1 ~ "Muito menos",
        valor == 2 ~ "Menos",
        valor == 3 ~ "Ideal",
        valor == 4 ~ "Mais",
        valor == 5 ~ "Muito mais"
      ),
      valor2 = fct_reorder(valor2, valor),
    ) %>% 
    ggplot(aes(x = valor2)) +
    geom_bar(fill = "orange", color = "black") +
    facet_wrap(~sabor) +
    labs(y = "Frequência", x = "JAR") +
    theme_bw()

plotly::ggplotly(p)
```


Column
------------------------------------------------

### Banana

```{r}
dados_jar_emp %>% 
  filter(!is.na(SAB_BANANA)) %>% 
  nrow %>% 
  valueBox(caption = "Banana", icon = "fa-users")
```

### Baunilha

```{r}
dados_jar_emp %>% 
  filter(!is.na(SAB_BAUNILHA)) %>% 
  nrow %>% 
  valueBox(caption = "Baunilha", icon = "fa-users")
```

### Maçã

```{r}
dados_jar_emp %>% 
  filter(!is.na(SAB_MACA)) %>% 
  nrow %>% 
  valueBox(caption = "Maçã", icon = "fa-users")
```

### Manga

```{r}
dados_jar_emp %>% 
  filter(!is.na(SAB_MANGA)) %>% 
  nrow %>% 
  valueBox(caption = "Manga", icon = "fa-users")
```

### Morango

```{r}
dados_jar_emp %>% 
  filter(!is.na(SAB_MORANGO)) %>% 
  nrow %>% 
  valueBox(caption = "Morango", icon = "fa-users")
```

Outros quesitos
=================================================

```{r}
dados_jar_emp %>%
  gather(sabor, valor_sabor, SAB_BAUNILHA:SAB_MANGA) %>% 
  gather(var, valor_var, SAB_BOCA:CONSIST) %>%
  group_by(sabor, var) %>% 
  count(valor_var) %>% 
  mutate(prop = n/sum(n)) %>% 
  ungroup() %>% 
  mutate(valor_var = as.factor(valor_var)) %>% 
  ggplot(aes(x = var, y = prop, fill = valor_var)) +
  geom_col() +
  facet_wrap(~sabor) +
  labs(y = "Proporção", x = "JAR") +
  theme_bw()
```

